package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/IORInterceptor_3_0.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u74/6087/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, January 29, 2016 5:44:11 PM PST
*/

public interface IORInterceptor_3_0 extends IORInterceptor_3_0Operations, org.omg.PortableInterceptor.IORInterceptor, org.omg.CORBA.portable.IDLEntity 
{
} // interface IORInterceptor_3_0
